---
- hosts: ec2-54-159-136-238.compute-1.amazonaws.com
  sudo: true
  remote_user: ec2-user
  tasks: 
      - name: Chnage dir to myjuniper
        command: ls -lrt
        args:
            chdir: /myjuniper